apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: tinycloud
  labels:
    app.kubernetes.io/name: blog
    app.kubernetes.io/component: blog
spec:
  selector:
    app.kubernetes.io/name: blog
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
