apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htmx-counter

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - resource-quota.yaml
  - network-policies.yaml

images:
  - name: ghcr.io/sasirulk/htmx-counter
    newTag: d7f5c74b23a4dad006b3ad7475347e880cb571aa
