apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{APP_NAME}}
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: newest-build
    allowTags: "regexp:^[a-f0-9]{40}$"
    pullSecret: pullsecret:argocd/ghcr-creds

  writeBackConfig:
    method: git
    gitConfig:
      branch: main

  applicationRefs:
    - namePattern: {{APP_NAME}}
      images:
        - alias: app
          imageName: {{IMAGE}}
