apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tinycloud-api
  namespace: tinycloud
  labels:
    app.kubernetes.io/name: tinycloud-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: tinycloud-platform
spec:
  ingressClassName: nginx
  rules:
    - host: api.tinycloud.local
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: tinycloud-api
                port:
                  number: 8080
