apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tinycloud

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml

images:
  - name: ghcr.io/sasirulk/tinycloud-platform-api
    newTag: f67788cea249eb0b647e80af115bb89a96b7d32e
