apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-5
  labels:
    app.kubernetes.io/name: react-app-5
    app.kubernetes.io/managed-by: tinycloud
    tinycloud.io/managed-by: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: react-app-5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: react-app-5
        tinycloud.io/managed-by: platform
    spec:
      imagePullSecrets:
        - name: ocir-creds
      containers:
        - name: react-app-5
          image: iad.ocir.io/idzghas4xwzv/tinycloud/react-app-5:a0eb6c07ecea25c6d68ef21c89cb2ac2542a0d38
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

