apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htmx-go-counter

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - resource-quota.yaml
  - network-policies.yaml

images:
  - name: ghcr.io/sasirulk/htmx-go-counter
    newTag: 12b1f816385463fc944147c64f089719cfe8f8b1
