apiVersion: v1
kind: Service
metadata:
  name: htmx-go-counter
  labels:
    app.kubernetes.io/name: htmx-go-counter
    tinycloud.io/managed-by: platform
spec:
  selector:
    app.kubernetes.io/name: htmx-go-counter
  ports:
    - port: 80
      targetPort: http
      name: http
