apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: tinycloud-api
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: tinycloud-api
      images:
        - alias: api
          imageName: iad.ocir.io/idzghas4xwzv/tinycloud/tinycloud-platform-api
  commonUpdateSettings:
    allowTags: "regexp:^[a-f0-9]{40}$"
    updateStrategy: newest-build
    pullSecret: pullsecret:argocd/ocir-creds
  writeBackConfig:
    method: git
    gitConfig:
      branch: main
