apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: tinycloud-demo
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: newest-build
    allowTags: "regexp:^[a-f0-9]{40}$"
    pullSecret: pullsecret:argocd/ocir-creds

  writeBackConfig:
    method: git
    gitConfig:
      branch: main

  applicationRefs:
    - namePattern: tinycloud-demo
      images:
        - alias: tinycloud
          imageName: iad.ocir.io/idzghas4xwzv/tinycloud/tinycloud-demo-app
