apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: blog
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: blog
      images:
        - alias: blog
          imageName: ghcr.io/sasirulk/blog
  commonUpdateSettings:
    allowTags: "regexp:^[a-f0-9]{40}$"
    updateStrategy: newest-build
    pullSecret: pullsecret:argocd/ghcr-creds
  writeBackConfig:
    method: git
    gitConfig:
      branch: main
