apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: tinycloud-demo
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: latest
    allowTags: "regexp:^[a-f0-9]{40}$"
    pullSecret: pullsecret:argocd/ghcr-creds

  writeBackConfig:
    method: git
    gitConfig:
      branch: main

  applicationRefs:
    - namePattern: tinycloud-demo
      images:
        - alias: tinycloud
          imageName: ghcr.io/sasirulk/tinycloud-demo-app
