apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tinycloud-platform-http
  namespace: tinycloud
  labels:
    app.kubernetes.io/name: tinycloud-platform
    app.kubernetes.io/part-of: tinycloud-platform
    app.kubernetes.io/component: ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tinycloud-platform.duckdns.org`)
      kind: Rule
      services:
        - name: oauth2-proxy
          port: 4180
      middlewares:
        - name: redirect-https
