apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tinycloud

resources:
  - namespace.yaml
  - oauth2-proxy.yaml
  - nginx-proxy.yaml
  - ingressroute.yaml
  - ingressroute-http.yaml
  - middleware-redirect-https.yaml
  - certificate.yaml
  - network-policies.yaml
