apiVersion: v1
kind: Service
metadata:
  name: react-app-4
  labels:
    app.kubernetes.io/name: react-app-4
    tinycloud.io/managed-by: platform
spec:
  selector:
    app.kubernetes.io/name: react-app-4
  ports:
    - port: 80
      targetPort: http
      name: http
