apiVersion: v1
kind: Secret
metadata:
    name: oauth2-github
    namespace: tinycloud
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:rptCYjgPSX6cDZdpCHdt56qTeHU=,iv:pzclw6qNeWAhMYeRlVnKsyW8jey+R591kx/2Jpqy+ws=,tag:gJX42SCKEz8RxJMhegJhWg==,type:str]
    client-secret: ENC[AES256_GCM,data:8FCxP/365tCP1SVEZRUKqdFgZuC30TWZk/oQsSUxoVLF6/3fGl0gpg==,iv:LrxnOd/AXX/P1WXpNEzw08s4hQbxwL21psbSZEqsz1o=,tag:Y9wIAX+EhxA4ler+hdukFg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:T/jn2IRPzJGGyl30PQG5Y5ffExC0RrITVJQEm/rOdRLO2m1pA89Ejg1NAoc=,iv:ct9uHxgisZpNE8xCuOS5m+T4ny1fS11jaXulHXTHMWo=,tag:bnI0Lx/kj4qNbUZy9h0TGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxfrs4d4kgx59lp56p3pmwpasssfyu2vtzcflcp5lswwagje0phqmhmn6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMUxqeUtzWnppWTYwRm1n
            WmNlcW9hR01Md2FVTnQ1L2NYcmFpOEhsVEY0CmJORmhqaXg1cFR4WVQzVWcrK05v
            dUpiVzA1WnhGTzNPdGJMSUR1eGJwbEEKLS0tIFZPV0NyOUNVbW14TzMvdUIvaWdF
            eFU4RWp6RUlHdjkzdDJsWWV1Q0xkK2sKCBYY6+XH7fabhdQGj/fcdZ+YDWhJ9For
            n2yh3ZVPik3wwWBjI6l3OBOFy1nOzw/+oj1/gexKxLm9X1zBLSWDZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T10:19:39Z"
    mac: ENC[AES256_GCM,data:1uvmRl3KeXJ8y+s4JZ72lg3RgvE/XfdzSue37jd+7vQjS1RtYMOyVXTgqYNfD9RihBKbzhJ5ncYl7krJCj2c0Khsh0JZy8lKpASRqRmSZ8wWfUwyrUGpH4zylyu3AofecRxVzN/yvONDISfD4dpGOfvko53jBArlqoDUqnfyYog=,iv:4rwb91F6Iwk8OU/qovaium/PmKUxnQislwzmDdLFy90=,tag:eMBOHLMyC8CMP3R02ZakPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|token|password|secret|key|privateKey|client-secret|cookie-secret)$
    version: 3.9.0
